[package]
name = "torch"
version = "0.1.0"
authors = ["Patrick Chan <patrickchan1999@gmail.com>"]

[dependencies]
plugins = { git = "https://github.com/torch-rs/plugins.git" }
settings = { git = "https://github.com/torch-rs/settings" }
sciter-rs = "*"